services:
  coupons-db:
    container_name: coupons-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    volumes:
      - ./mssql:/var/opt/mssql
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=StrongPassword!123
      - MSSQL_DB=coupons
