apiVersion: v1
kind: Service
metadata:
  name: front-coupons
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80 # Puerto externo que expondrás
    targetPort: 80 # Puerto interno en el contenedor
  selector:
    role: front-coupons