apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-coupons
spec:
  replicas: 1
  selector:
    matchLabels:
      role: back-coupons
  template:
    metadata:
      labels:
        role: back-coupons
    spec:
      containers:
      - name: back-coupons
        image: luisrojasdev/back-coupons:1.0
        ports:
        - containerPort: 8080 # Puerto interno en el contenedor